Numpy

Numpy is a powerful Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

In [2]:
import numpy as np

# Create a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr)

# Create a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.arange(0,10,2)
print("Original array:", arr)

# Checking the shape of the array
print("Shape of arr:", arr.shape)

# Reshaping the array to 3 rows and 4 columns
arr_reshaped = arr.reshape(1,5)
print("Reshaped array (1*5):\n", arr_reshaped)

# Checking the shape of the reshaped array
print("Shape of arr_reshaped:",arr_reshaped.shape)

Original array: [0 2 4 6 8]
Shape of arr: (5,)
Reshaped array (3x4):
 [[0 2 4 6 8]]
Shape of arr_reshaped: (1, 5)


In [5]:
np.ones((2, 3))  # Create a 2x3 array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#identity matrix
np.eye(3)  # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attributes of the array
print("Original array:", arr)
print("Shape of arr:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type of elements:", arr.dtype)
print("Size of each element in bytes:", arr.itemsize)
print("Total number of elements:", arr.size)

Original array: [0 2 4 6 8]
Shape of arr: (5,)
Number of dimensions: 1
Data type of elements: int64
Size of each element in bytes: 8
Total number of elements: 5


In [8]:
#numPy vectorized operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
arr_sum = arr1 + arr2
print("Element-wise addition:", arr_sum)

# Element-wise multiplication
arr_product = arr1 * arr2   
print("Element-wise multiplication:", arr_product)

Element-wise addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]


In [9]:
#Universal functions (ufuncs)

arr = np.array([1, 2, 3, 4, 5])
# Square root of each element
arr_sqrt = np.sqrt(arr)
print("Square root of each element:", arr_sqrt)
# Exponential of each element
arr_exp = np.exp(arr)
print("Exponential of each element:", arr_exp)
# Sine of each element
arr_sin = np.sin(arr)
print("Sine of each element:", arr_sin)
# Logarithm of each element
arr_log = np.log(arr)
print("Logarithm of each element:", arr_log)

Square root of each element: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of each element: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine of each element: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Logarithm of each element: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [13]:
#array indexing and slicing
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

# Accessing elements
print("First element:", arr[0][0])


First element: 1


In [14]:
print(arr[1:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [16]:
print(arr[1:,2:])

[[ 8  9 10]
 [13 14 15]]


In [18]:
print(arr[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
#modifying the array
arr[1:]=100
print(arr)

[[  1   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [3]:
#normalization

data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev=np.std(data)

#normalized data
normal_data=(data-mean)/std_dev
print(normal_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [7]:
#logical operation

da=np.array([1,2,3,4,5])

print(da>2)
print(da[da>2])

[False False  True  True  True]
[3 4 5]
